version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php73dev
            - php73prod
    php73dev:
        build:
          context: ./images/php73dev
          args:
            username: php
            userid: 1000
            usergroupid: 1000
        links:
            - mysql8
        volumes:
            - ./www:/var/www
            - /usr/local/etc/php/conf.d
            - ./php/php73dev/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./shared/tmp/xhprof:/tmp/xhprof
    php73prod:
        build:
          context: ./images/php73prod
          args:
            username: php
            userid: 1000
            usergroupid: 1000
        links:
            - mysql8
        volumes:
            - ./www:/var/www
            - /usr/local/etc/php/conf.d
            - ./php/php73prod/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./shared/tmp/xhprof:/tmp/xhprof
    mysql8:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/8/db:/var/lib/mysql
            - /usr/local/bin
        environment:
            MYSQL_ROOT_PASSWORD: secret
