# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php73dev
            - php73prod
    php73dev:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php73dev
        # этот образ будет общаться с mysql
        links:
            - mysql8
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
            - /usr/local/etc/php/conf.d
            - ./php/php73dev/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    php73prod:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php73prod
        # этот образ будет общаться с mysql
        links:
            - mysql8
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
            - /usr/local/etc/php/conf.d
            - ./php/php73prod/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            #- ./php/php73prod/xhprof:/tmp/xhprof
    mysql8:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/8/db:/var/lib/mysql
            - /usr/local/bin
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret
